// <auto-generated />
using System;
using InvestSimples.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InvestSimples.Api.Migrations
{
    [DbContext(typeof(InvestContext))]
    partial class InvestContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("InvestSimples.Api.Models.Ativo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAtivo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Moeda")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrecoAtual")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("VariacaoDia")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("Codigo", "UsuarioId")
                        .IsUnique();

                    b.ToTable("Ativos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Codigo = "PETR4",
                            DataAtualizacao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAtivo = true,
                            Moeda = "BRL",
                            Nome = "Petrobras PN",
                            PrecoAtual = 35.50m,
                            Tipo = "Ações",
                            UsuarioId = 1,
                            VariacaoDia = 2.15m
                        },
                        new
                        {
                            Id = 2,
                            Codigo = "VALE3",
                            DataAtualizacao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAtivo = true,
                            Moeda = "BRL",
                            Nome = "Vale ON",
                            PrecoAtual = 68.90m,
                            Tipo = "Ações",
                            UsuarioId = 1,
                            VariacaoDia = -1.20m
                        },
                        new
                        {
                            Id = 3,
                            Codigo = "CDB001",
                            DataAtualizacao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAtivo = true,
                            Moeda = "BRL",
                            Nome = "CDB Banco X 110% CDI",
                            PrecoAtual = 1000.00m,
                            Tipo = "Renda Fixa",
                            UsuarioId = 1,
                            VariacaoDia = 0.05m
                        },
                        new
                        {
                            Id = 4,
                            Codigo = "LCI001",
                            DataAtualizacao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAtivo = true,
                            Moeda = "BRL",
                            Nome = "LCI Banco Y 95% CDI",
                            PrecoAtual = 1000.00m,
                            Tipo = "Renda Fixa",
                            UsuarioId = 1,
                            VariacaoDia = 0.03m
                        },
                        new
                        {
                            Id = 5,
                            Codigo = "HGLG11",
                            DataAtualizacao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAtivo = true,
                            Moeda = "BRL",
                            Nome = "HGLG11 - FII Logística",
                            PrecoAtual = 185.40m,
                            Tipo = "Fundos",
                            UsuarioId = 1,
                            VariacaoDia = 1.80m
                        },
                        new
                        {
                            Id = 6,
                            Codigo = "USD/BRL",
                            DataAtualizacao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAtivo = true,
                            Moeda = "BRL",
                            Nome = "Dólar Americano",
                            PrecoAtual = 5.25m,
                            Tipo = "Câmbio",
                            UsuarioId = 1,
                            VariacaoDia = 0.45m
                        },
                        new
                        {
                            Id = 7,
                            Codigo = "EUR/BRL",
                            DataAtualizacao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAtivo = true,
                            Moeda = "BRL",
                            Nome = "Euro",
                            PrecoAtual = 5.65m,
                            Tipo = "Câmbio",
                            UsuarioId = 1,
                            VariacaoDia = -0.20m
                        },
                        new
                        {
                            Id = 8,
                            Codigo = "BTC/BRL",
                            DataAtualizacao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAtivo = true,
                            Moeda = "BRL",
                            Nome = "Bitcoin",
                            PrecoAtual = 265000.00m,
                            Tipo = "Cripto",
                            UsuarioId = 1,
                            VariacaoDia = 3.50m
                        },
                        new
                        {
                            Id = 9,
                            Codigo = "IBOV",
                            DataAtualizacao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAtivo = true,
                            Moeda = "PONTOS",
                            Nome = "IBOVESPA",
                            PrecoAtual = 125000.00m,
                            Tipo = "Índice",
                            UsuarioId = 1,
                            VariacaoDia = 1.20m
                        });
                });

            modelBuilder.Entity("InvestSimples.Api.Models.Simulacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AporteMensal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DataSimulacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("PrazoMeses")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("RendimentoTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TaxaAnual")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("TotalInvestido")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ValorFinal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorInicial")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Simulacoes");
                });

            modelBuilder.Entity("InvestSimples.Api.Models.Transacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AtivoId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataTransacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrecoUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AtivoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Transacoes");
                });

            modelBuilder.Entity("InvestSimples.Api.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UltimoLogin")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            DataCriacao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "teste@investsimples.com",
                            Nome = "Usuário Teste",
                            SenhaHash = "$2a$11$4dPSHSI0FAH8fLAsMk4hLesKK.6q.QVLujD7FyJ35N/jAOVggfIc2"
                        });
                });

            modelBuilder.Entity("InvestSimples.Api.Models.Ativo", b =>
                {
                    b.HasOne("InvestSimples.Api.Models.Usuario", "Usuario")
                        .WithMany("Ativos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("InvestSimples.Api.Models.Simulacao", b =>
                {
                    b.HasOne("InvestSimples.Api.Models.Usuario", "Usuario")
                        .WithMany("Simulacoes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("InvestSimples.Api.Models.Transacao", b =>
                {
                    b.HasOne("InvestSimples.Api.Models.Ativo", "Ativo")
                        .WithMany("Transacoes")
                        .HasForeignKey("AtivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InvestSimples.Api.Models.Usuario", "Usuario")
                        .WithMany("Transacoes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ativo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("InvestSimples.Api.Models.Ativo", b =>
                {
                    b.Navigation("Transacoes");
                });

            modelBuilder.Entity("InvestSimples.Api.Models.Usuario", b =>
                {
                    b.Navigation("Ativos");

                    b.Navigation("Simulacoes");

                    b.Navigation("Transacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
